export const Category = [
  { id: 0, name: "Renewable Energy" },
  { id: 1, name: "Agriculture" },
  { id: 2, name: "Green Energy" },
  { id: 3, name: "Food Waste" },
  { id: 4, name: "Green Building" },
  { id: 5, name: "Clean Water" },
  { id: 6, name: "Biodiversity" },
  { id: 7, name: "Waste Management" },
  { id: 8, name: "Transportation" },
  { id: 9, name: "Climate Change" },
  { id: 10, name: "Tourism" },
  { id: 11, name: "Healthcare" },
  { id: 12, name: "Education" },
  { id: 13, name: "E-waste" },
  { id: 14, name: "Global Warming" },
];
